language: perl

os:
  - linux
  
perl:
  #- "5.6"
  - "5.8"
  #- "5.10"        
  #- "5.12"         
  #- "5.14"         
  #- "5.16"         
  #- "5.18"         
  #- "5.20"         
  #- "5.22"         
  #- "5.24"         
  #- "5.26"         
  #- "5.28"         
  - "5.30"         
  #- "blead"  
  
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - cpan Test::Simple  

install:
  - perl -V
  - cpan-install --deps
  # Force latest version of these modules
  - cpanm Scalar::Util
  - cpanm Perl::OSType
  - cpanm IO::Uncompress::Unzip
  - cpanm IO::Compress::Zip  
  - cpanm IO::Compress::Lzma
