language: perl

os:
  - linux
  
perl:
  - "5.6"
  - "5.8"
  #- "5.10"        
  #- "5.12"         
  #- "5.14"         
  #- "5.16"         
  #- "5.18"         
  #- "5.20"         
  #- "5.22"         
  #- "5.24"         
  #- "5.26"         
  #- "5.28"         
  - "5.30"         
  #- "blead"  
  
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - perl -V
  # Force latest versions of prereq modules 
  # The cpan-install line is enough for perl >= 5.8
#   - cpan-install  --update-prereqs --deps
  
# install:
#   - perl -V
#   # Force latest versions of prereq modules 
#   # The cpan-install line is enough for perl >= 5.8
#   - cpan-install  --update-prereqs --deps

# Force latest versions of prereq modules
# cpanm not supported on 5.6, so use cpan
jobs:
  include:
  - perl: "5.6"
    install:
      - cpan Scalar::Util
      - cpan Perl::OSType
      - cpan IO::Uncompress::Unzip
      - cpan IO::Compress::Zip  
      - cpan IO::Compress::Lzma
   - perl: "5.30"
    install:
      - cpan-install  --update-prereqs --deps
