language: perl

os:
  - linux
  
perl:
  - "5.6"
  #- "5.8"
  #- "5.10"        
  #- "5.12"         
  #- "5.14"         
  #- "5.16"         
  #- "5.18"         
  #- "5.20"         
  #- "5.22"         
  #- "5.24"         
  #- "5.26"         
  #- "5.28"         
  - "5.30"         
  #- "blead"  
    
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - perl -V
  # Force latest versions of prereq modules 
  # The cpan-install line is enough for perl >= 5.8
  - cpan-install  --update-prereqs --deps
  
# install:
#   - perl -V
#   - echo $TRAVIS_PERL_VERSION
# #   # Force latest versions of prereq modules
# #   # The cpan-install line is enough for perl >= 5.8
#   - cpan-install  --update-prereqs --deps

install: >
  if  [ "$TRAVIS_PERL_VERSION" = "5.6" ]; then
    echo here!!!!
    cpan Scalar::Util;
    cpan Perl::OSType;
    cpan IO::Uncompress::Unzip;
    cpan IO::Compress::Zip  ;
    cpan IO::Compress::Lzma;
  fi


